apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: admin@goodhouse.io
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
    - dns01:
        webhook:
          groupName: acme.namecheap.com
          solverName: namecheap
          config:
            apiKeySecretRef:
              key: apiKey
              name: namecheap-credentials-sandbox
            apiUserSecretRef:
              key: apiUser
              name: namecheap-credentials-sandbox
            useSandbox: true
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: admin@goodhouse.io
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - dns01:
        webhook:
          groupName: acme.namecheap.com
          solverName: namecheap
          config:
            apiKeySecretRef:
              key: apiKey
              name: namecheap-credentials
            apiUserSecretRef:
              key: apiUser
              name: namecheap-credentials
