- name: start Docker container
  docker_container:
    name: influxdb
    image: influxdb:{{ influxdb.version }}
    cleanup: true
    detach: true
    published_ports:
    - 8086:8086
    pull: true
    restart_policy: always
    volumes:
    - /opt/influxdb:/var/lib/influxdb
    env:
      INFLUXDB_DB: openhab
      INFLUXDB_HTTP_AUTH_ENABLED: 'true'
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_USER: openhab
    comparisons:
      env: strict
  tags: influxdb
