- name: start Docker container
  docker_container:
    name: grafana
    image: grafana/grafana:{{ version }}
    cleanup: true
    detach: true
    published_ports:
    - 3000:3000
    pull: true
    restart_policy: always
    volumes:
    - /opt/grafana:/var/lib/grafana
    env:
      GF_INSTALL_PLUGINS: natel-discrete-panel
    comparisons:
      env: strict
  tags: grafana
