---
- hosts: rpi
  roles:
  - role: common
  - role: rpi

- hosts: k3s_nodes
  vars:
    k3s_become_for_all: true
    k3s_build_cluster: false
    k3s_release_version: stable
    k3s_start_on_boot: true
    k3s_state: installed
    k3s_server:
      default-local-storage-path: /opt/k8s
  roles:
   - role: xanmanning.k3s
   - role: manifests
