---
- name: Add /etc/ssh/sshd_config.d/10-settings.conf
  template:
    src: settings.conf.j2
    dest: /etc/ssh/sshd_config.d/10-settings.conf
  notify: reload ssh
  tags:
  - ssh

- name: Install common packages
  apt:
    pkg:
    - python3-pip
    update_cache: true
  tags:
  - apt

- name: Install common Python packages via pip
  pip:
    name:
    - openshift
    - pyyaml
  tags:
  - pip
  - python
