---
- name: Configure /etc/ssh/sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: reload ssh
  tags:
  - ssh

- name: Install common packages
  apt:
    pkg:
    - python3-pip
    update_cache: true
  tags:
  - apt

- name: Install common Python packages via pip
  pip:
    name:
    - openshift
    - pyyaml
  tags:
  - pip
  - python
